use std::error::Error;

pub fn solution() -> Result<(), Box<dyn Error>> {
    Ok(())
}
